import json
from pathlib import Path

nb_path = Path('notebooks/ablation_kaggle.ipynb')
with open(nb_path, encoding='utf-8') as f:
    nb = json.load(f)

# The registration code needs to:
# 1. Define the full modules
# 2. Inject into ultralytics.nn.tasks.__dict__ AND ultralytics.nn.modules.__dict__
# 3. Patch tasks.py so that any internal import finds SvelteNeck & F3M
injection_cell_source = [
    "import ultralytics.nn.tasks as tasks\n",
    "import ultralytics.nn.modules as modules\n",
    "from pathlib import Path\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "\n",
    "class EHConv(nn.Module):\n",
    "    def __init__(self, c1, c2, k=3, s=1):\n",
    "        super().__init__()\n",
    "        p = k // 2\n",
    "        self.dw = nn.Conv2d(c1, c1, k, s, p, groups=c1, bias=False)\n",
    "        self.pw = nn.Conv2d(c1, c2, 1, bias=False)\n",
    "        self.bn = nn.BatchNorm2d(c2)\n",
    "        self.act = nn.Mish()\n",
    "    def forward(self, x):\n",
    "        return self.act(self.bn(self.pw(self.dw(x))))\n",
    "\n",
    "class EHSBottleneck(nn.Module):\n",
    "    def __init__(self, c1, c2, shortcut=True, e=1.0, k=5, s=1):\n",
    "        super().__init__()\n",
    "        h = int(c2 * e)\n",
    "        self.cv1 = EHConv(c1, h, k=1)\n",
    "        self.cv2 = EHConv(h, c2, k=k, s=s)\n",
    "        self.add = shortcut and c1 == c2 and s == 1\n",
    "    def forward(self, x):\n",
    "        return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))\n",
    "\n",
    "class EHSCSP(nn.Module):\n",
    "    def __init__(self, c1, c2, n=1, shortcut=True, e=1.0, k=5):\n",
    "        super().__init__()\n",
    "        h = int(c2 * e)\n",
    "        self.cv1 = nn.Sequential(nn.Conv2d(c1, 2*h, 1, bias=False), nn.BatchNorm2d(2*h), nn.Mish())\n",
    "        self.blocks = nn.ModuleList([EHSBottleneck(h, h, shortcut=shortcut, e=1., k=k) for _ in range(n)])\n",
    "        self.cv2 = nn.Sequential(nn.Conv2d((n+2)*h, c2, 1, bias=False), nn.BatchNorm2d(c2), nn.Mish())\n",
    "    def forward(self, x):\n",
    "        x = self.cv1(x)\n",
    "        p, t = torch.chunk(x, 2, dim=1)\n",
    "        s = [p, t]\n",
    "        for b in self.blocks:\n",
    "            t = b(t)\n",
    "            s.append(t)\n",
    "        return self.cv2(torch.cat(s, dim=1))\n",
    "\n",
    "class SvelteNeck(nn.Module):\n",
    "    def __init__(self, e=0.50):\n",
    "        super().__init__()\n",
    "        self.upsample_p5 = nn.Upsample(scale_factor=2, mode='nearest')\n",
    "        self.td_p4 = EHSCSP(384, 128, n=1, shortcut=True, e=e, k=5)\n",
    "        self.upsample_p4 = nn.Upsample(scale_factor=2, mode='nearest')\n",
    "        self.td_p3 = EHSCSP(256, 64,  n=1, shortcut=True, e=e, k=5)\n",
    "        self.bu_p3_down = EHConv(64,  64,  k=3, s=2)\n",
    "        self.bu_p4 = EHSCSP(192, 128, n=1, shortcut=True, e=e, k=5)\n",
    "        self.bu_p4_down = EHConv(128, 128, k=3, s=2)\n",
    "        self.bu_p5 = EHSCSP(384, 256, n=1, shortcut=True, e=e, k=5)\n",
    "    def forward(self, F):\n",
    "        p3, p4, p5 = F\n",
    "        u5 = self.upsample_p5(p5)\n",
    "        t4 = self.td_p4(torch.cat([u5, p4], 1))\n",
    "        u4 = self.upsample_p4(t4)\n",
    "        t3 = self.td_p3(torch.cat([u4, p3], 1))\n",
    "        d3 = self.bu_p3_down(t3)\n",
    "        b4 = self.bu_p4(torch.cat([d3, t4], 1))\n",
    "        d4 = self.bu_p4_down(b4)\n",
    "        b5 = self.bu_p5(torch.cat([d4, p5], 1))\n",
    "        return [t3, b4, b5]\n",
    "\n",
    "class F3M(nn.Module):\n",
    "    def __init__(self, c, r=4, sk=7):\n",
    "        super().__init__()\n",
    "        rd = max(1, c // r)\n",
    "        self.cg = nn.Sequential(\n",
    "            nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n",
    "            nn.Linear(c, rd, bias=False), nn.ReLU(inplace=True),\n",
    "            nn.Linear(rd, c, bias=False), nn.Sigmoid())\n",
    "        self.sg = nn.Sequential(\n",
    "            nn.Conv2d(c, c, sk, 1, sk//2, groups=c, bias=False),\n",
    "            nn.BatchNorm2d(c), nn.Sigmoid())\n",
    "    def forward(self, x):\n",
    "        cg = self.cg(x).view(x.shape[0], x.shape[1], 1, 1)\n",
    "        return x * cg * self.sg(x)\n",
    "\n",
    "# Direct injection into tasks.__dict__ and modules.__dict__\n",
    "for k, v in {'SvelteNeck': SvelteNeck, 'F3M': F3M, 'EHConv': EHConv, 'EHSCSP': EHSCSP}.items():\n",
    "    tasks.__dict__[k] = v\n",
    "    modules.__dict__[k] = v\n",
    "\n",
    "# Also write to disk and patch tasks.py\n",
    "tasks_file = Path(tasks.__file__)\n",
    "t_content = tasks_file.read_text(encoding='utf-8')\n",
    "if 'from .modules import SvelteNeck' not in t_content and 'SvelteNeck' not in t_content[:500]:\n",
    "    header = 'from ultralytics.nn.modules import SvelteNeck, F3M\\n'\n",
    "    # tasks_file.write_text(header + t_content, encoding='utf-8')\n",
    "\n",
    "print('Ultralytics custom modules successfully registered:', SvelteNeck.__name__, F3M.__name__)\n"
]

nb['cells'][5]['source'] = injection_cell_source

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print('Updated cell 5 in notebooks/ablation_kaggle.ipynb successfully!')
